# question_data = [
# {"question": "A slug's blood is green.", "correct_answer": "True"},
# {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
# {"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
# {"question": "The total surface area of a human lungs is the size of a football pitch.", "correct_answer": "True"},
# {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
#  "correct_answer": "True"},
# {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#  "correct_answer": "False"},
# {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
# {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
# {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
# {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
# {"question": "No piece of square dry paper can be folded in half more than 7 times.", "correct_answer": "False"},
# {"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"}
# ]
###easy
# question_data = [
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "Scotland voted to become an independent country during the referendum from September 2014.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge", "question": "Pluto is a planet.",
#          "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "Dihydrogen Monoxide is a dangerous chemical.", "correct_answer": "False",
#          "incorrect_answers": ["True"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#                                           "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
#                                           "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
#          "incorrect_answers": ["True"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#                                           "question": "The color orange is named after the fruit.",
#                                           "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#          "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True",
#          "incorrect_answers": ["False"]},
#         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#                                            "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
#                                            "correct_answer": "True", "incorrect_answers": ["False"]}
# ]
###medium
# question_data = [
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The commercial UK channel ITV stands for \"International Television\".",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The French word for 'glass' is 'glace'.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The scientific name for the Southern Lights is Aurora Australis?",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The French word to travel is 'Travail'", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The average woman is 5 inches(13 centimeters) shorter than the average man.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "Fast food restaurant chains Carl's Jr. and Hardee's are owned by the same company.",
#      "correct_answer": "True", "incorrect_answers": ["False"]}
# ]
###filmeasy
question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Brandon Routh plays the titular character in the movie 'John Wick'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Shaquille O'Neal appeared in the 1997 film 'Space Jam'.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
    "question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "'Minions' was released on the June 10th, 2015.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
    "question": "Han Solo's co-pilot and best friend, 'Chewbacca', is an Ewok.",
    "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "'Foodfight!' earned less than $80,000 at box office.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
    "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
    "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
